### PR TITLE
moves primitives to package primitive

### PR DESCRIPTION
**Pull request by MikkelHJuul**
fixes requiring namespace overriding of this package as an import

```go
import primitive "github.com/csimplestring/go-left-right"
```
becomes
```go
import "github.com/csimplestring/go-left-right/primitive"
```

This also had to fix the issue that I have addressed in my earlier PR (moving to primitive) exposes the bug

### CODE REVIEW

**Comment by MikkelHJuul** [comment]
I accidentally merged some additional changes here (https://github.com/csimplestring/go-left-right/pull/3/commits/6d0f3abe26ae315f373046ba05aaa43d1630e36f)

**Comment by csimplestring** [comment]
> I accidentally merged some additional changes here ([6d0f3ab](https://github.com/csimplestring/go-left-right/commit/6d0f3abe26ae315f373046ba05aaa43d1630e36f))

so you want to roll back?

**Comment by MikkelHJuul** [comment]
@csimplestring - you decide

**Comment by csimplestring** [comment]
@MikkelHJuul  after a night of thinking, I agree to un-export those 3 functions, which makes this library more easy to use, only ApplyReadFn and ApplyWriteFn are public.

Can you resolve the conflicts? so we can finally merge

**Comment by MikkelHJuul** [comment]
@csimplestring - done :)

**Pull request merged**
